### PR TITLE
Fix UCS2 string comparison

### LINKED ISSUE #797: Invalid string comparison
```haxe
class Main {
	static public function main() {
		var s = "𠜎zя";
		var s2 = "abя";
		trace(s > s2);
	}
}
```
That yields `false` on cpp, `true` on all other targets.

### PR DESCRIPTION
**Pull request by RealyUniqueName**
Fixes #797
Unblocks https://github.com/HaxeFoundation/haxe/pull/8298

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Fixed CI

File: src/String.cpp [hunk 1]
```diff
@@ -1534,7 +1534,21 @@ int String::compare(const ::String &inRHS) const
```
Comment (Aurel300) [inline src/String.cpp]: (Cannot comment on the actual lines 1532 and 1533) There is now `String::isUTF16Encoded()`, which is an `inline` function that's basically identical to the flag check above, so `s0IsWIde` and `s1IsWide` can be defined in a more readable way.

**Comment by RealyUniqueName** [comment]
> I would also drop the whitespace changes, but that's a detail.

 There is only 4 trailing whitespaces trimmed. And the rest of the file doesn't have trailing whitespaces.
